package search

import (
	"errors"
	"fmt"

	"github.com/sevein/guggmeta/Godeps/_workspace/src/github.com/olivere/elastic"
	log "github.com/sevein/guggmeta/Godeps/_workspace/src/gopkg.in/inconshreveable/log15.v2"
)

const (
	TIMEOUT = "1"
)

var s *Search

type Search struct {
	urls  []string
	index string

	*elastic.Client
	log.Logger
}

func Start(urls []string, index string) (*Search, error) {
	s := &Search{
		urls:   urls,
		index:  index,
		Logger: log.New("module", "search"),
	}

	c, err := elastic.NewClient(
		elastic.SetSniff(false),
		elastic.SetHealthcheck(false),
		elastic.SetURL(urls...))
	if err != nil {
		return nil, errors.New("Client could not be created")
	}
	s.Client = c

	s.Logger.Info("Start cluster check (ping)")
	for _, url := range urls {
		info, code, err := s.Client.Ping().Timeout(TIMEOUT).URL(url).Do()
		if err != nil {
			return nil, errors.New("Connection failed (ping error)")
		}
		s.Logger.Info(fmt.Sprintf("Ping cluster node %s", url), "code", code, "version", info.Version.Number)
	}

	// Create index
	exists, err := s.Client.IndexExists(index).Do()
	if err != nil {
		return nil, err
	}
	if !exists {
		s.Logger.Info("Create index", "index", index)
		if _, err := s.Client.CreateIndex(index).Do(); err != nil {
			return nil, err
		}
	}

	// Open index
	s.Logger.Info("Open index", "index", index)
	if _, err := s.Client.OpenIndex(index).Do(); err != nil {
		return nil, err
	}

	// Register types and mappings
	if err := checkTypes(s, index); err != nil {
		s.Logger.Info("Register types and mappings", "index", index)
		if err := registerTypes(s, index); err != nil {
			return nil, err
		}
	}

	return s, nil
}

func (s *Search) Stop() {
	s.Client.Stop()
}

func (s *Search) Count() (int64, error) {
	return s.Client.Count(s.index).Do()
}

// Index walks the directory with all the submissions generated by ggmdownload
// and populates the search index in Elasticsearch
func (s *Search) Index(dataDir string) error {
	s.Logger.Info("Index documents in given directory", "dir", dataDir)

	indexSubmissions(s, dataDir, s.index)

	// Is there anything else that we want to index?
	// ...

	return nil
}
